### ISSUE TITLE
Clarify write behavior

### ISSUE THREAD

**Issue by paulrberg** [wighawag/hardhat-preprocessor#1]
Hey Ronan, great work, as usual!

I think that there are two conflicting statements in the RADME:

> Note that this plugin, by default, does not touch the filesystem. It happens in memory.

And later you say:

> This task will write the modification to disk. By default it overwrite the sources. if the dest option is set, it will write in that folder instead (and keep sources intact).

So which one is it? Does `hardhat-preprocessor` modify my source contract by default, or not?

**Comment by wighawag** [comment]
@PaulRBerg thanks for your feedback.

the `preprocess` task was added later. It is actually not needed. 

The plugin will automatically preprocess source file **in memory** based on the configuration setup in `hardhat.config.ts`

The `preprocess` task is useful if you want such processing to be then written to disk, either on the same files or in a different destination folder.

Maybe I should call it differently. any suggestion ?

I'll revisit the readme to make it more clear.

**Comment by PaulRBerg** [comment]
Oh, I see! Thanks for confirming.

> Maybe I should call it differently. any suggestion ?

Maybe "parse"? Don't know, naming is always tough.

**Comment by wighawag** [comment]
Thanks, I added some more text to explain hopefully better the 2 different behavior
